### ISSUE TITLE
Post still uploads even when file size is too big

### ISSUE THREAD

**Issue by Klyntar5** [lolgreatjcc/Readdit#102]
The post upload should be stopped, and this error should be properly handled as too big a file crashes the backend server

**Comment by TYRPRO** [comment]
Reopening to comment. Checks if the file is of the correct type, and is smaller than the maximum file size (< 10MB for image/gif and < 100MB for video). If not, reject. 
Also, media upload is now attempted first before creating post, this is to prevent the problem of a post being created despite the media upload failing after. Fixed in PR #107.
