### ISSUE TITLE
Clicking on individual posts in saved posts (profile) leads to an error.

### ISSUE THREAD

**Issue by TYRPRO** [lolgreatjcc/Readdit#144]
The href for the post div in the saved posts is missing the subreaddit name, which is undefined in the link. Also, users should be able to see the entire content of the post instead of only the title.

**Comment by lolgreatjcc** [comment]
> The href for the post div in the saved posts is missing the subreaddit name, which is undefined in the link. Also, users should be able to see the entire content of the post instead of only the title.

href for the post div is supposed to be undefined, then the post.html javascript handles it by redirecting them to the correct subreaddit. also I purposely made it so that only the title is shown as if they wanted to know more about the post they'd click on the post saving us the faff of having to implement media here too.
